<div>
  <label>注册</label>
  <hr></hr>
</div>
<div>
  <form action="/user/doregister" method="post">
  	<div>
  	  <label>用户名</label>
      <input type="text" name="username" />
    </div>
    <div>
      <label>密码</label>	
      <input type="password" name="password" />
    </div>
    <div>
      <label>确认密码</label>	
      <input type="password" name="repassword" />
    </div>
    <div>
      <input type="submit" name="submit" value="submit" />
    </div>
  </form>
</div>
